---
#- name: "setup | install zabbix repository"
#  yum_repository:
#    name: "{{ item.name }}"
#    description: "{{ item.description }}"
#    baseurl: "{{ item.baseurl }}"
#    gpgcheck: "{{item.gpgcheck }}"
#    gpgkey: "{{ item.gpgkey }}"
#    mode: "{{ item.mode | default('0644') }}"
#    priority: "{{  item.priority | default('99') }}"
#    state: "{{ item.state | default('present') }}"
#  with_items: "{{ zabbix_repo_yum }}"
#  register: yum_repo_installed
#  become: yes
#  tags:
#    - zabbix-server

- name: "setup | install zabbix repository"
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present

- name: "setup | installing zabbix-server-{{ zabbix_server_database }}"
  package:
    pkg: "{{ zabbix_server_package }}"
    state: "{{ zabbix_server_package_state }}"
    enablerepo: zabbix
  register: zabbix_server_package_installed
  become: yes
  tags:
    - zabbix-server

- name: "setup | enabler redhat software collections"
  yum:
    name: centos-release-scl
    state: present

- name: "setup | install zabbix frontend"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zabbix-web-pgsql-scl
    - zabbix-apache-conf-scl
